name: Build and Release Iris

on:
  push:
    tags:
      - 'v*' # Trigger the workflow when you push a tag starting with 'v' (e.g., v1.0.0)
  workflow_dispatch: # Allow you to manually trigger the workflow from the Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Run Build Script
      run: .\build.bat
      shell: cmd

    - name: Rename Executable
      run: Rename-Item "dist\Iris.exe" "Iris-${{ github.ref_name }}-win-x64.exe"
      
    - name: Upload Artifact (Executable)
      uses: actions/upload-artifact@v4
      with:
        name: Iris-Executable
        path: dist/Iris-${{ github.ref_name }}-win-x64.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/Iris-${{ github.ref_name }}-win-x64.exe
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
